### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by rororomeda** [phucbm/flickity-responsive#15]
It's a great library, thank you!

**Comment by rororomeda** [comment]
oh, actually there is an issue in 2.0.4:
When draggable and wrapAround are both enabled, it's not possible to drag infinitely.
The problem doesn't occur in 2.0.1.

**Comment by rororomeda** [comment]
oh, actually there is an issue in version >= 2.0.3:
When draggable and wrapAround are both enabled, it's not possible to drag infinitely.
The problem doesn't occur in version <= 2.0.2.

```
this.flkty = new FlickityResponsive( slideshow, {
 	cellAlign: 'left',
 	prevNextButtons: false,
	pageDots: true,
	wrapAround: true,	
	autoPlay: false,
	draggable: true,
	selectedAttraction: 0.013,
	friction: 0.26,
	dragThreshold: 1,
	adaptiveHeight: true,
	imagesLoaded:true,
	responsive: [{
		breakpoint: 768,
		settings: {
			draggable: true
		}
		}]	
});
```

**Comment by phucbm** [comment]
Hi, could you check this out in the [v2.0.6](https://github.com/phucbm/flickity-responsive/releases/tag/v2.0.6) release? 

Seems to be fixed.

**Comment by rorothegreatest** [comment]
It seems to work, yes. Thank you
