### ISSUE TITLE
How to destroy

### ISSUE THREAD

**Issue by rororomeda** [phucbm/flickity-responsive#21]
How can I properly destroy an instance of FlickityResponsive?

entity.flickity('destroy'); doesn't work.

**Comment by phucbm** [comment]
Are you using jQuery? jQuery is not fully supported in FlickityResponsive. You can initialize using jQuery but for further usage, please use the vanilla JS way.

```js
// init
jQuery('.carousel').flickityResponsive({});

// get instance
const flkty = Flickity.data( '.carousel' );

// using API
flkty.destroy();
```

**Comment by rororomeda** [comment]
@phucbm 
I understand. Thank you!
